# Generated by Django 4.1.7 on 2023-03-10 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_alter_course_lecturers"),
        ("assessments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assessment",
            name="course_name",
        ),
        migrations.AddField(
            model_name="assessment",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.course",
            ),
            preserve_default=False,
        ),
    ]
