# Generated by Django 4.1.7 on 2023-03-11 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("assessments", "0002_remove_assessment_course_name_assessment_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assessment",
            name="email",
        ),
        migrations.RemoveField(
            model_name="assessment",
            name="lecturer",
        ),
        migrations.RemoveField(
            model_name="assessment",
            name="uuid",
        ),
        migrations.AddField(
            model_name="assessment",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
