# Generated by Django 4.1.7 on 2023-03-11 13:03

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_alter_course_lecturers"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="color",
            field=models.CharField(
                default=courses.models.get_random_color, max_length=7
            ),
        ),
    ]
